version: '3'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: myuser
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
      
  myapp:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
